version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Containerfile
    container_name: data-ingestion-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
      - /home/rsi/etc/pushover.env
    volumes:
      - ./app:/app/app:ro
      - ./logs:/app/logs
